spring:
  application:
    name: project
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:5432/${POSTGRES_DB:project}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  cache:
    cache-names:
      - rate-limit-buckets-project
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8080
  forward-headers-strategy: NATIVE

jwt:
  secret-key: ${JWT_SECRET:55d731c263e1ddb8e50eec214ccf010207b82cfb415c76976751a12f1f04c2ca}
  ttl: 60 # in minutes